from typing import Protocol

from app.analytics.domain.models.sales_metric import SalesMetric, GenreStats, SalesTrend
from app.analytics.domain.models.order_metric import OrderMetric
from app.analytics.domain.models.product_catalog_entry import ProductCatalogEntry


class SalesMetricRepository(Protocol):
    def save(self, metric: SalesMetric) -> None: ...
    def find_by_product_id(self, product_id: str) -> list[SalesMetric]: ...
    def get_genre_stats(self) -> list[GenreStats]: ...
    def get_sales_trend(self, days: int = 7) -> list[SalesTrend]: ...
    def get_top_products(self, limit: int = 10) -> list[dict]: ...
    def get_total_revenue(self) -> float: ...
    def get_total_units_sold(self) -> int: ...


class OrderMetricRepository(Protocol):
    def save(self, metric: OrderMetric) -> None: ...
    def get_orders_count(self) -> int: ...
    def get_average_order_value(self) -> float: ...


class ProductCatalogRepository(Protocol):
    def save(self, entry: ProductCatalogEntry) -> None: ...
    def count(self) -> int: ...
