from typing import Protocol

from app.domain.models.user import User


class UserRepository(Protocol):
    async def save(self, user: User) -> None: ...
    async def find_by_id(self, user_id: str) -> User | None: ...
    async def find_by_username(self, username: str) -> User | None: ...
    async def find_by_email(self, email: str) -> User | None: ...
