from typing import Protocol
from app.inventory.domain.models.book import Book


class BookRepository(Protocol):
    async def find_by_id(self, book_id: str) -> Book | None: ...
    async def find_by_isbn(self, isbn: str) -> Book | None: ...
    async def save(self, book: Book) -> None: ...
    async def delete(self, book_id: str) -> None: ...
    async def has_orders(self, book_id: str) -> bool: ...
